# Generated by Django 6.0.7 on 2026-07-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
