# Generated by Django 6.0.7 on 2026-07-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
