# Generated by Django 6.0.7 on 2026-07-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_images/'),
        ),
    ]
